version: "3"
services: 
    backend:
        restart: always
        build: 
            context: .
            dockerfile: ./Dockerfile
        env_file: ./.env
        ports:
            - 3000:3000

    
    admin-dashboad:
        restart: always
        build: 
            context: ../CulumbusDashboard/
            dockerfile: ../CulumbusDashboard/Dockerfile
        ports:
            - 5000:5000

    

